name: .NET Linting & Build & Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract .NET version from csproj
      id: dotnet-version
      run: |
        VERSION=$(grep -oP '(?<=<TargetFramework>net)[0-9.]+' src/MembankCore/MembankCore.csproj)
        echo "detected_version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ steps.dotnet-version.outputs.detected_version }}

    - name: Linting
      run: |
        dotnet format --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" `
        --results-directory ./coverage `
        -- `
        DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*Test*]*,[xunit*]*,][*/tests/*]"

    - name: Generate Coverage Reports
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.1
      with:
        reports: 'coverage/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'MarkdownSummary'

    - name: Upload Coverage Summary
      run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

